name: A bite of code
markdown: redcarpet
highlighter: rouge
author_info:
  weibo: weibo.com/appenginelover
  github: github.com/hoozecn
  email: hoozecn (at) gmail.com
  google_plus: plus.google.com/+ZhiminWu
  stackoverflow: https://stackoverflow.com/users/965002/hoozecn
exclude: [token, publish.sh, Gemfile, Gemfile.lock, vendor]